using System;
using Modular_Assemblies.AssemblyScripts.AssemblyComponents;
using Modular_Assemblies.AssemblyScripts.DebugUtils;
using Sandbox.ModAPI;
using VRage.Game.ModAPI;

namespace Modular_Assemblies.AssemblyScripts.Commands
{
    /// <summary>
    ///     Stores methods for commands in CommandHandler.
    /// </summary>
    internal static class CommandMethods
    {
        public static void PollAssemblies(string[] args)
        {
            ModularLog.LogAndChat("Assembly Poll", $"{AssemblyPartManager.I.AllPhysicalAssemblies.Count} assemblies found:");
            foreach (var assembly in AssemblyPartManager.I.AllPhysicalAssemblies)
            {
                ModularLog.LogAndChat($"  [ID {assembly.Key}]", $"[DEFID {assembly.Value.AssemblyDefinition.Name}] {assembly.Value.ComponentParts.Count} parts ({(assembly.Value.IsClosing ? "Closing" : "Open")})");
                foreach (var part in assembly.Value.ComponentParts)
                {
                    ModularLog.LogAndChat($"  [ID {assembly.Key}]", $"  PartId {part.PartIdUnsafe}");
                    IMyGps gps = MyAPIGateway.Session.GPS.Create($"ASM {assembly.Key}", "Autogenerated by !md poll",
                        part.Block.GetPosition(), true, true);
                    gps.DiscardAt = new TimeSpan(0, 0, 15);
                    MyAPIGateway.Session.GPS.AddLocalGps(gps);
                }
            }
            ModularLog.LogAndChat("Assembly Poll", $"{AssemblyPartManager.I.AllGridLogics.Count} grid managers found:");
            foreach (var gridMan in AssemblyPartManager.I.AllGridLogics)
            {
                ModularLog.LogAndChat($"  [ID {gridMan.Key.EntityId}]", $"{gridMan.Value.AllAssemblyParts.Count} definitions:");
                foreach (var assembly in gridMan.Value.AllAssemblyParts)
                {
                    ModularLog.LogAndChat($"    [DEFID {assembly.Key.Name}]", $"{assembly.Value.Values.Count} parts");
                }
            }
        }
    }
}